#ifndef DEWFORD_TREND_H
#define DEWFORD_TREND_H

#include "type.h"

struct easyword
{
    u16 code;
    const char name_jp[30];
    const char name_en[30];
    const char name_fr[30];
    const char name_de[30];
    const char name_it[30];
    const char name_sp[30];
};

const static struct easyword easyword_CONDITIONS[69]=
{
    {0x1400,"あつい","HOT","CHAUD","HEISS","ALTRUISMO","BONDADOSO"},
    {0x1401,"あった","EXISTS","EXISTE","EXISTIERT","VIRTÙ","BONDADOSA"},
    {0x1402,"あまり","EXCESS","EXCES","ÜBERMÄSSIG","BUONE","LEAL"},
    {0x1403,"あり","APPROVED","APPROUVE","GENEHMIGT","BUONI","FUERTE"},
    {0x1404,"ある","HAS","LENT","HAT","BUONA","MIEDO"},
    {0x1405,"いい","GOOD","BON","FEIN","BUONO","ÚNICO"},
    {0x1406,"いか","LESS","LENTEUR","WENIGER","È BRAVO","ÚNICA"},
    {0x1407,"いきおい","MOMENTUM","VITESSE","SCHWUNG","DI SLANCIO","RAPIDÍSIMA"},
    {0x1408,"いける","GOING","FACILITE","GEHEN","È BRAVA","RAPIDÍSIMO"},
    {0x1409,"いじょう","WEIRD","BIZARRE","VERRÜCKT","SONO BRAVI","FURIA"},
    {0x140A,"いそがしい","BUSY","OCCUPE","BESCHÄFTIGT","CON CORAGGIO","CERTERO"},
    {0x140B,"いっしょに","TOGETHER","ENSEMBLE","ZUSAMMEN","VIVACITÀ","CERTERA"},
    {0x140C,"いっぱい","FULL","PLEIN","VOLL","CREDO IN TE","FUERTES"},
    {0x140D,"いない","ABSENT","ABSENT","ABWESEND","SONO GRANDE","SAGAZ"},
    {0x140E,"いや","BEING","ETANT","SEINE","BONTÀ","GENIAL"},
    {0x140F,"いる","NEED","J'AI BESOIN","BRAUCHE","CORTESIA","CORDIAL"},
    {0x1410,"うまい","TASTY","DELICIEUX","LECKER","SAPIDA","MAÑOSO"},
    {0x1411,"うまく","SKILLED","DOUE","GESCHICKT","TALENTO","MAÑOSA"},
    {0x1412,"うるさい","NOISY","BRUYANT","LAUT","BON TON","ASTUTO"},
    {0x1413,"おおきい","BIG","ENORME","GROSS","SEI GRANDE","ASTUTA"},
    {0x1414,"おくれ","LATE","TARD","SPÄT","EFFICACE","CARISMÁTICOS"},
    {0x1415,"おしい","CLOSE","PROCHE","NAHE BEI","EFFICACI","PACIENTE"},
    {0x1416,"おとなしい","DOCILE","DOCILE","SANFTMÜTIG","AFFABILE","DÓCIL"},
    {0x1417,"おもしろい","AMUSING","AMUSANT","AMÜSANT","DIVERTENTI","GRACIOSO"},
    {0x1418,"おもしろく","ENTERTAINING","DISTRAYANT","UNTERHALTSAM","DIVERTENTE","GRACIOSA"},
    {0x1419,"かんぺき","PERFECTION","PERFECTION","PERFEKTION","PERFEZIONE","CONSTANTE"},
    {0x141A,"けっこう","PRETTY","JOLI","HÜBSCH","AFFABILI","SERENO"},
    {0x141B,"げんき","HEALTHY","EN FORME","GESUND","TI STUPIRÀ","SERENA"},
    {0x141C,"さいこう","EXCELLENT","REMARQUABLE","EXZELLENT","ECCELLENTE","RESPETUOSO"},
    {0x141D,"さかさま","UPSIDE DOWN","BEBETE","UMGEDREHT","ECCELLENTI","RESPETUOSA"},
    {0x141E,"さむい","COLD","FROID","KALT","TRAVOLGENTI","SEGURO"},
    {0x141F,"さわやか","REFRESHING","FRAIS","ERFRISCHEND","TROPPO FORTE","SEGURA"},
    {0x1420,"しかたない","UNAVOIDABLE","INEVITABLE","UNVERMEIDBAR","NATURALI","TENAZ"},
    {0x1421,"すごい","MUCH","IGNORANT","VIELE","TI AMMIRO","AMABLE"},
    {0x1422,"すごすぎ","OVERWHELMING","IRRESISTIBLE","MITREISSEND","TRAVOLGENTE","PRUDENTE"},
    {0x1423,"すてき","FABULOUS","FABULEUX","FABELHAFT","UNA FAVOLA","RESPONSABLE"},
    {0x1424,"たいした","ELSE","NUNUCHE","ANDERES","AMMIRAZIONE","DISCRETO"},
    {0x1425,"たかい","EXPENSIVE","CHER","TEUER","FENOMENALE","DISCRETA"},
    {0x1426,"ただしい","CORRECT","CORRECTEMENT","RICHTIG","FENOMENALI","CORRECTA"},
    {0x1427,"だめ","IMPOSSIBLE","IMPOSSIBLE","UNMÖGLICH","CHE FENOMENO","CORRECTO"},
    {0x1428,"ちいさい","SMALL","PETIT","KLEIN","FENOMENO","MODERADO"},
    {0x1429,"ちがう","DIFFERENT","DIFFERENT","VERSCHIEDENE","SEI UN MITO","MODERADA"},
    {0x142A,"つかれ","TIRED","FATIGUE","MÜDE","SONO UN MITO","RESISTENTE"},
    {0x142B,"とくい","SKILL","HABILETE","GESCHICK","ABILITÀ","RÁPIDO"},
    {0x142C,"トップ","TOP","MAXIMUM","TOP","SEI AL TOP","RÁPIDA"},
    {0x142D,"とまらない","NON-STOP","NON-STOP","NONSTOP","SONO AL TOP","SENSIBLE"},
    {0x142E,"とんでもない","PREPOSTEROUS","RIDICULE","ABSURD","È IL MASSIMO","FOGOSA"},
    {0x142F,"ない","NONE","AUCUN","KEIN","VI AMMIRO","FOGOSO"},
    {0x1430,"なかった","NOTHING","RIEN","NICHTS","SONO GRANDI","SILENCIOSO"},
    {0x1431,"なし","NATURAL","NATUREL","NATÜRLICH","NATURALE","SILENCIOSA"},
    {0x1432,"なって","BECOMES","DEVIENT","WIRD","SONO FORTI","CAPAZ"},
    {0x1433,"ぬるい","LUKEWARM","TIEDE","LAUWARM","CHI TI BATTE","REFLEXIVO"},
    {0x1434,"はやい","FAST","RAPIDE","SCHNELL","MI STUPISCI","REFLEXIVA"},
    {0x1435,"ひくい","LOW","BAS","NIEDRIG","TI STUPIRÒ","ENÉRGICO"},
    {0x1436,"ひどい","AWFUL","TERRIBLE","SCHLIMM","LAVORA SODO","ENÉRGICA"},
    {0x1437,"ひとりで","ALONE","SEUL","ALLEINE","IN FORMA","SENSATO"},
    {0x1438,"ひま","BORED","JE M'ENNUIE","GELANGWEILT","ECCEZIONALE","SENSATA"},
    {0x1439,"ひみつ","SECRET","SECRET","GEHEIMNIS","ECCEZIONALI","HUMILDE"},
    {0x143A,"ふしぎ","MYSTERY","MYSTERE","GEHEIM","SEGRETO","MISTERIOSO"},
    {0x143B,"ふそく","LACKS","IL MANQUE","FEHLT","SIMPATIA","ENIGMÁTICO"},
    {0x143C,"ベスト","BEST","MEILLEUR","BESTES","SIETE GRANDI","ENIGMÁTICA"},
    {0x143D,"へた","LOUSY","MINABLE","LAUSIG","SONO MITICI","VELOZ"},
    {0x143E,"まちがって","MISTAKE","ERREUR","FEHLER","SIAMO MITICI","ÁGIL"},
    {0x143F,"やさしい","KIND","AGREABLE","HÖFLICH","IMBATTIBILE","EVASIVO"},
    {0x1440,"よく","WELL","PIRE","SCHLECHT","IMBATTIBILI","EVASIVA"},
    {0x1441,"よわって","WEAKENED","AFFAIBLI","GESCHWÄCHT","CREDO IN VOI","SENCILLO"},
    {0x1442,"らく","SIMPLE","SIMPLE","EINFACH","SEMPLICE","SENCILLA"},
    {0x1443,"らしい","SEEMS","ON DIRAIT","SCHEINBAR","SEMPLICI","DIVERTIDA"},
    {0x1444,"わるい","BADLY","GRAVEMENT","MIES","VALORE","DIVERTIDO"},
};

const static struct easyword easyword_LIFESTYLE[45]=
{
    {0x1800,"アルバイト","CHORES","ROUTINE","PFLICHTEN","COMPITI","RUTINA"},
    {0x1801,"うち","HOME","MAISON","HEIM","CASA","HOGAR"},
    {0x1802,"おかね","MONEY","ARGENT","GELD","SOLDI","DINERO"},
    {0x1803,"おこづかい","ALLOWANCE","TRANSPORTS","TASCHENGELD","PAGHETTA","PAGA SEMANAL"},
    {0x1804,"おふろ","BATH","BAIN","BAD","BAGNO","BAÑO"},
    {0x1805,"かいわ","CONVERSATION","CONVERSATION","GESPRÄCH","DIALOGO","CHARLAR"},
    {0x1806,"がっこう","SCHOOL","ECOLE","SCHULE","SCUOLA","COLEGIO"},
    {0x1807,"きねん","COMMEMORATE","ANNIVERSAIRE","GEDENKEN","CELEBRAZIONE","CUMPLEAÑOS"},
    {0x1808,"くせ","HABIT","HABITUDES","GEWOHNHEIT","ABITUDINE","HÁBITOS"},
    {0x1809,"グループ","GROUP","GROUPE","GRUPPE","GRUPPO","AMIGOS"},
    {0x180A,"ことば","WORD","MOT","WORT","PAROLA","PRENSA"},
    {0x180B,"コンビニ","STORE","MAGASIN","LAGER","MAESTRO","MERCADO"},
    {0x180C,"サービス","SERVICE","SERVICE","SERVICE","LAVAGNA","TRÁFICO"},
    {0x180D,"しごと","WORK","TRAVAIL","ARBEIT","LAVORO","TRABAJO"},
    {0x180E,"システム","SYSTEM","SYSTEME","SYSTEM","SISTEMA","AUTOBÚS"},
    {0x180F,"しゅぎょう","TRAIN","TRAIN","TRAINIEREN","TRENO","METRO"},
    {0x1810,"じゅぎょう","CLASS","CLASSE","LEKTION","AULA","CLASES"},
    {0x1811,"じゅく","LESSONS","DEVOIRS","UNTERRICHT","LEZIONI","DEBERES"},
    {0x1812,"じょうほう","INFORMATION","INFORMATIONS","INFORMATION","INFORMAZIONI","DESAYUNAR"},
    {0x1813,"せいかつ","LIVING","QUOTIDIEN","LEBENDIG","VIVA LA VITA","MERENDAR"},
    {0x1814,"せんせい","TEACHER","PROFESSEUR","LEHRER","INSEGNANTE","PROFESOR"},
    {0x1815,"たいかい","TOURNAMENT","TOURNOI","TURNIER","TORNEO","CENAR"},
    {0x1816,"てがみ","LETTER","LETTRE","BRIEF","LETTERA","CORREO"},
    {0x1817,"できごと","EVENT","EVENEMENT","GESCHEHEN","EVENTO","EVENTO"},
    {0x1818,"デジタル","DIGITAL","NUMERIQUE","DIGITALES","TECNOLOGIA","NOTAS"},
    {0x1819,"テスト","TEST","CONTROLE","TEST","PALLONE","EXÁMENES"},
    {0x181A,"デパート","DEPT. STORE","EPICERIE","KAUFHAUS","NEGOZIO","TIENDAS"},
    {0x181B,"テレビ","TELEVISION","TELEVISION","FERNSEHER","TELEVISIONE","TELEVISIÓN"},
    {0x181C,"でんわ","PHONE","TELEPHONE","TELEFON","TELEFONO","TELÉFONO"},
    {0x181D,"どうぐ","ITEM","OBJET","ITEM","STRUMENTO","RECREO"},
    {0x181E,"なまえ","NAME","NOM","NAME","NOME","DUCHARSE"},
    {0x181F,"ニュース","NEWS","NOUVELLES","NEUIGKEITEN","NOTIZIE","PAN"},
    {0x1820,"にんき","POPULAR","CELEBRE","POPULÄR","MAESTRA","CINE"},
    {0x1821,"パーティー","PARTY","FETE","PARTY","FESTA","TEATRO"},
    {0x1822,"べんきょう","STUDY","ETUDIER","LERNEN","STUDIO","ESTUDIOS"},
    {0x1823,"マシン","MACHINE","ORDINATEUR","MASCHINE","MACCHINA","COCHES"},
    {0x1824,"メール","MAIL","COURRIER","POST","MESSAGGIO","PELUQUERÍA"},
    {0x1825,"メッセージ","MESSAGE","MESSAGE","MITTEILUNG","POSTA","MENSAJES"},
    {0x1826,"やくそく","PROMISE","PROMESSE","VERSPRECHEN","PROMESSA","PARQUE"},
    {0x1827,"ゆめ","DREAM","REVE","TRAUM","SOGNO","AULA"},
    {0x1828,"ようちえん","KINDERGARTEN","MATERNELLE","KINDERGARTEN","ASILO","PISCINA"},
    {0x1829,"ライフ","LIFE","VIE","LEBEN","VITA","PLAYA"},
    {0x182A,"ラジオ","RADIO","RADIO","RADIO","RADIO","RADIO"},
    {0x182B,"レンタル","RENTAL","LOYER","MIETE","E-MAIL","REÍR"},
    {0x182C,"ワールド","WORLD","MONDE","WELT","MONDO","LLORAR"},
};

const static struct easyword easyword_HOBBIES[54]=
{
    {0x1A00,"アイドル","IDOL","STAR","IDOL","IDOLO","ÍDOLO"},
    {0x1A01,"アニメ","ANIME","DESSIN ANIME","ANIME","ROCK","DORMIR"},
    {0x1A02,"うた","SONG","CHANSON","SONG","SCIARE","CANTAR"},
    {0x1A03,"えいが","MOVIE","CINEMA","FILM","CINEMA","PELÍCULAS"},
    {0x1A04,"おかし","SWEETS","BONBONS","NASCHEN","DOLCI","GOLOSINAS"},
    {0x1A05,"おしゃべり","CHAT","DISCUTER","PLAUDERN","CHAT","CHATEAR"},
    {0x1A06,"おままごと","CHILD'S PLAY","JEU D'ENFANT","KINDERSPIEL","GIOCHI","JUEGO"},
    {0x1A07,"おもちゃ","TOYS","JOUETS","SPIELZEUG","GIOCATTOLI","JUGUETES"},
    {0x1A08,"おんがく","MUSIC","MUSIQUE","MUSIK","MUSICA","MÚSICA"},
    {0x1A09,"カード","CARDS","CARTES","KARTENSPIELE","FIGURINE","CROMOS"},
    {0x1A0A,"かいもの","SHOPPING","SHOPPING","EINKAUFEN","SHOPPING","COMPRAS"},
    {0x1A0B,"カメラ","CAMERA","PHOTOGRAPHIE","FOTOS","FOTOGRAFIA","FOTOGRAFÍA"},
    {0x1A0C,"かんしょう","VIEWING","FOYER","BESICHTIGUNG","ESCURSIONE","EXPOSICIONES"},
    {0x1A0D,"かんせん","SPECTATOR","THEATRE","ZUSCHAUER","TEATRO","ESPECTÁCULOS"},
    {0x1A0E,"グルメ","GOURMET","CUISINE","GOURMET","CUCINARE","COMER BIEN"},
    {0x1A0F,"ゲーム","GAME","JEUX","SPIEL","GIOCARE","CANICAS"},
    {0x1A10,"ごっこ","RPG","JEUX DE ROLE","RPG","INFORMATICA","VIDEOJUEGOS"},
    {0x1A11,"コレクション","COLLECTION","COLLECTION","SAMMLUNG","COLLEZIONARE","COLECCIONES"},
    {0x1A12,"コンプリート","COMPLETE","JEUX VIDEO","KOMPLETT","SCAMBIARE","MAGIA"},
    {0x1A13,"ざっし","MAGAZINE","MAGAZINES","MAGAZIN","MANGIARE","REVISTAS"},
    {0x1A14,"さんぽ","WALK","COURSE","SPAZIEREN","CAMMINARE","PASEAR"},
    {0x1A15,"じてんしゃ","BIKE","VELO","FAHRRAD","BICI","CICLISMO"},
    {0x1A16,"しゅみ","HOBBY","HOBBY","HOBBY","HOBBY","ESTUDIAR"},
    {0x1A17,"スポーツ","SPORTS","SPORT","SPORT","SPORT","DEPORTES"},
    {0x1A18,"ソフト","SOFTWARE","LOGICIELS","SOFTWARE","SOFTWARE","INTERNET"},
    {0x1A19,"ソング","SONGS","CHANTER","SONGS","CANZONE","VÍDEOS"},
    {0x1A1A,"ダイエット","DIET","DIETETIQUE","NAHRUNG","CANTARE","COCINAR"},
    {0x1A1B,"たからもの","TREASURE","TRESORS","KOSTBARKEIT","FRANCOBOLLI","DARDOS"},
    {0x1A1C,"たび","TRAVEL","VOYAGES","REISEN","VIAGGIARE","VIAJAR"},
    {0x1A1D,"ダンス","DANCE","DANSE","TANZEN","BALLARE","BAILAR"},
    {0x1A1E,"チャンネル","CHANNEL","CHAINE","WASSERSPORT","LA TV","EXCURSIÓN"},
    {0x1A1F,"つくり","MAKING","BRICOLAGE","HERSTELLUNG","VEDERE","ARTESANÍA"},
    {0x1A20,"つり","FISHING","PECHE","ANGELN","PESCARE","PESCAR"},
    {0x1A21,"デート","DATE","RENDEZ-VOUS","VERABREDUNG","USCIRE","CITAS"},
    {0x1A22,"デザイン","DESIGN","DESSIN","DESIGN","DISEGNARE","DISEÑAR"},
    {0x1A23,"でんしゃ","LOCOMOTIVE","PETIT TRAIN","LOKOMOTIVEN","TRENINI","TRENES"},
    {0x1A24,"ぬいぐるみ","PLUSH DOLL","NOUNOURS","PLÜSCHPUPPEN","PELUCHE","PELUCHE"},
    {0x1A25,"パソコン","PC","INFORMATIQUE","PC","PC","PC"},
    {0x1A26,"はな","FLOWERS","JARDINAGE","BLUMEN","FIORI","FLORES"},
    {0x1A27,"ヒーロー","HERO","HEROS","HELD","CAMPIONE","HÉROES"},
    {0x1A28,"ひるね","NAP","SIESTE","NICKERCHEN","DORMIRE","SIESTA"},
    {0x1A29,"ヒロイン","HEROINE","HEROINE","HELDIN","CAMPIONESSA","CAMPAMENTO"},
    {0x1A2A,"ファッション","FASHION","MODE","MODE","MODA","MODA"},
    {0x1A2B,"ぼうけん","ADVENTURE","AVENTURE","ABENTEUER","AVVENTURA","AVENTURA"},
    {0x1A2C,"ボード","BOARD","BATEAU","BRETTSPIELE","DA TAVOLO","JUEGOS MESA"},
    {0x1A2D,"ボール","BALL","FOOTBALL","BALL","CALCIO","PELOTA"},
    {0x1A2E,"ほん","BOOK","LIVRE","BÜCHER","LEGGERE","LIBROS"},
    {0x1A2F,"まつり","FESTIVAL","FESTIVALS","FESTIVALS","CORRERE","DISFRACES"},
    {0x1A30,"まんが","COMICS","BD","COMICS","FUMETTI","CÓMICS"},
    {0x1A31,"やすみ","HOLIDAY","VACANCES","FERIEN","OZIARE","FIESTA"},
    {0x1A32,"よてい","PLANS","LECTURE","ETWAS PLANEN","MODELLISMO","MAQUETAS"},
    {0x1A33,"りゅうこう","TRENDY","A LA MODE","SCHICKIMICKI","GIOCO","REFRANES"},
    {0x1A34,"りょこう","VACATION","TOURISME","URLAUB","VACANZE","VACACIONES"},
    {0x1A35,"ルック","LOOK","COCOONING","AUSSEHEN","SCRIVERE","DANZA"},
};


struct DewfordTrend
{
    u16 trendiness:7;
    u16 maxTrendiness:7;
    u16 gainingTrendiness:1;
    //u16 padding:1;
    u16 rand;
    u16 words[2];
    char name1[30];
    char name2[30];
};
#define SAVED_TRENDS_COUNT 5
static struct DewfordTrend dewfordTrends[SAVED_TRENDS_COUNT];

struct PlayerID
{
    u16 SID;
    u16 TID;
};
static struct PlayerID PlayerID;

#endif